### ISSUE TITLE
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv3_METHOD'

### ISSUE THREAD

**Issue by Neri-hV** [alfredodeza/scraping-demo#1]
Hello, I was trying to do the laboratory : Parse HTML with Scrapy and XPath from weel 3 
https://www.coursera.org/learn/scripting-with-python-sql-for-data-engineering-duke/ungradedLab/JX51C/parse-html-with-scrapy-and-xpath
After following the first steps, when I wrote in the terminal: 
```
scrapy shell  "./html/1992_World_Junior_Championships_in_Athletics_–_Men's_high_jump"
```
I have the following error:

```
(venv) coder@b0e397ab729b:~/scrapy-xpath$ scrapy shell "./html/1992_World_Junior_Championships_in_Athletics_–_Men's_high_jump"
2023-03-24 14:07:32 [scrapy.utils.log] INFO: Scrapy 2.5.1 started (bot: scrapybot)
2023-03-24 14:07:32 [scrapy.utils.log] INFO: Versions: lxml 4.9.2.0, libxml2 2.9.14, cssselect 1.2.0, parsel 1.7.0, w3lib 2.1.1, Twisted 22.10.0, Python 3.8.10 (default, Nov 26 2021, 20:14:08) - [GCC 9.3.0], pyOpenSSL 23.1.0 (OpenSSL 3.1.0 14 Mar 2023), cryptography 40.0.0, Platform Linux-5.15.0-1017-aws-x86_64-with-glibc2.29
2023-03-24 14:07:32 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor
2023-03-24 14:07:32 [scrapy.crawler] INFO: Overridden settings:
{'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter',
 'LOGSTATS_INTERVAL': 0}
2023-03-24 14:07:32 [scrapy.extensions.telnet] INFO: Telnet Password: 96852358a5712ac4
2023-03-24 14:07:32 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage']
2023-03-24 14:07:32 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "http"
Traceback (most recent call last):
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/handlers/__init__.py", line 49, in _load_handler
    dhcls = load_object(path)
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/utils/misc.py", line 61, in load_object
    mod = import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http11.py", line 23, in <module>
    from scrapy.core.downloader.contextfactory import load_context_factory_from_settings
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/contextfactory.py", line 11, in <module>
    from scrapy.core.downloader.tls import DEFAULT_CIPHERS, openssl_methods, ScrapyClientTLSOptions
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/tls.py", line 23, in <module>
    METHOD_SSLv3: SSL.SSLv3_METHOD,                     # SSL 3 (NOT recommended)
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv3_METHOD'
2023-03-24 14:07:32 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "https"
Traceback (most recent call last):
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/handlers/__init__.py", line 49, in _load_handler
    dhcls = load_object(path)
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/utils/misc.py", line 61, in load_object
    mod = import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http11.py", line 23, in <module>
    from scrapy.core.downloader.contextfactory import load_context_factory_from_settings
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/contextfactory.py", line 11, in <module>
    from scrapy.core.downloader.tls import DEFAULT_CIPHERS, openssl_methods, ScrapyClientTLSOptions
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/tls.py", line 23, in <module>
    METHOD_SSLv3: SSL.SSLv3_METHOD,                     # SSL 3 (NOT recommended)
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv3_METHOD'
2023-03-24 14:07:32 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.s3.S3DownloadHandler" for scheme "s3"
Traceback (most recent call last):
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/handlers/__init__.py", line 49, in _load_handler
    dhcls = load_object(path)
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/utils/misc.py", line 61, in load_object
    mod = import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/handlers/s3.py", line 3, in <module>
    from scrapy.core.downloader.handlers.http import HTTPDownloadHandler
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http11.py", line 23, in <module>
    from scrapy.core.downloader.contextfactory import load_context_factory_from_settings
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/contextfactory.py", line 11, in <module>
    from scrapy.core.downloader.tls import DEFAULT_CIPHERS, openssl_methods, ScrapyClientTLSOptions
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/tls.py", line 23, in <module>
    METHOD_SSLv3: SSL.SSLv3_METHOD,                     # SSL 3 (NOT recommended)
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv3_METHOD'
Traceback (most recent call last):
  File "/home/coder/scrapy-xpath/venv/bin/scrapy", line 8, in <module>
    sys.exit(execute())
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/cmdline.py", line 145, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/cmdline.py", line 100, in _run_print_help
    func(*a, **kw)
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/cmdline.py", line 153, in _run_command
    cmd.run(args, opts)
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/commands/shell.py", line 68, in run
    crawler.engine = crawler._create_engine()
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/crawler.py", line 101, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/__init__.py", line 83, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/utils/misc.py", line 61, in load_object
    mod = import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/downloadermiddlewares/retry.py", line 27, in <module>
    from scrapy.core.downloader.handlers.http11 import TunnelError
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http11.py", line 23, in <module>
    from scrapy.core.downloader.contextfactory import load_context_factory_from_settings
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/contextfactory.py", line 11, in <module>
    from scrapy.core.downloader.tls import DEFAULT_CIPHERS, openssl_methods, ScrapyClientTLSOptions
  File "/home/coder/scrapy-xpath/venv/lib/python3.8/site-packages/scrapy/core/downloader/tls.py", line 23, in <module>
    METHOD_SSLv3: SSL.SSLv3_METHOD,                     # SSL 3 (NOT recommended)
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv3_METHOD'
(venv) coder@b0e397ab729b:~/scrapy-xpath$ 
```

**Comment by alfredodeza** [comment]
@Neri-hV I've updated the instructions and removed the lab from Coursera since that seems to have some limitations. Sorry you are facing these, but I appreciate a ton you are reporting them so that I can fix them. 

I've replaced the lab with a _Reading_ that has instructions on how to open the lab with Codespaces with this repository template: https://github.com/alfredodeza/scrapy-xpath 

That template has everything for the lab. Please let me know how that works out for you.
